server:
  port: 8081
spring:
  datasource:
    name: commondemo
    url: jdbc:mysql://localhost:3306/commondemo?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动


mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.wh.lawliet.entity #配置实体类